---
title: "Einführung in die Datenanalyse und -visualisierung mit R"
author: "Dozent: Pekka Sagner M.Sc."
date: "Wintersemester 2021/22"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Lernergebnisse (learning outcomes) / Kompetenzen
Studierende sind nach Absolvieren des Kurses in der Lage, eigene Datenanalysen mit dem Statistikprogramm R durchzuführen. Die Studierenden sind sensibilisiert für die Arbeit mit Daten und führen explorative Datenanalysen und -visualisierungen selbständig durch. Studierende lernen die Grammatik der Grafiken (grammar of graphics) und die Grundlagen reproduzierbarer Forschung durch literarisches Programmieren.

Der Kurs richtet sich an Studierende mit Interesse an der praktischen Datenanalyse. Im Kurs lernen die Studierenden die Grundkonzepte der Datenanalyse: Einlesen, Ordnen, Transformieren, Visualisieren, Modellieren und Kommunizieren. 

Im Kurs wird die Software R und RStudio genutzt. R ist eine über viele wissenschaftliche Disziplinen hinweg weitverbreitete Programmiersprache. Der Kurs bietet einen modernen Einstieg in die Datenanalyse mit dem *Tidyverse*, einer Sammlung von Paketen, die das Programmieren mit R besonders nutzerfreundlich macht und zur Beliebtheit der Programmiersprache beiträgt. 

Der Kurs besteht auf Vorlesungs- und Übungszeiten sowie selbständiger Eigenleistung in Form von Übungsaufgaben. Im Vorlesungsteil werden Konzepte und Strukturen theoretisch eingeführt, die in den praktischen Übungsteilen vertieft werden.

Die Philosophie des Kurses ist »Hands-On«. Ein Großteil der Zeit wird deshalb auf die praktischen Teile verwendet werden.

### Inhalte

+ Grundlagen des Programmierens
+ Grundlagen der Programmiersprache R
+ Explorative Datenanalyse


### Teilnahmevoraussetzungen

Formal: Keine. 

Inhaltlich: Keine.

### Voraussetzungen für die Vergabe von Kreditpunkten

Präsenz und Bearbeiten der Übungsaufgaben

<!-- ```{r, include=F} -->
<!-- library(tidyverse) -->
<!-- # library(kableExtra) -->
<!-- library(knitr) -->

<!-- kursplan <- tibble(Stunde = c("1. Stunde",  -->
<!--                               "2. Stunde", -->
<!--                               "3. Stunde", -->
<!--                               "4. Stunde"), -->
<!--        Kursinhalte = c("Grundverständnis Kursziele, Erste Schritte mit R und RStudio",  -->
<!--                        "Arbeitsfluss mit R und RStudio: Benutzeroberfläche, Skripte und Projekte", -->
<!--                        "Vektoren, Matrizen und andere Formate", -->
<!--                        "Explorative Datenanalyse mit dem Tidyverse I") -->
<!-- ) -->
<!-- ```  -->

<!-- ```{r, echo=F} -->
<!-- kursplan %>%   -->
<!--           kableExtra::kbl(booktabs = T) %>%  -->
<!--           kableExtra::kable_styling(latex_options = c("striped")) -->
<!-- ``` -->

